### ISSUE TITLE
`yarn lint:js` error for Ember Concurreny Task syntax

### ISSUE THREAD

**Issue by alexdiliberto** [NullVoxPopuli/eslint-plugin-decorator-position#14]
Error:
```
$ yarn lint:js
yarn run v1.22.4
$ eslint . --ext .ts --ext .js
TypeError: Cannot read property '0' of undefined
Occurred while linting /Users/alex/Repos/polarity/neontetra/app/components/channel-selector.js:155
    at normalizeConfig (/Users/alex/Repos/polarity/neontetra/node_modules/eslint-plugin-decorator-position/lib/rules/decorator-position.js:269:18)
    at placeDecoratorsBesideProperty (/Users/alex/Repos/polarity/neontetra/node_modules/eslint-plugin-decorator-position/lib/rules/decorator-position.js:182:20)
    at /Users/alex/Repos/polarity/neontetra/node_modules/eslint-plugin-decorator-position/lib/rules/decorator-position.js:167:9
    at Array.forEach (<anonymous>)
    at positionDecorator (/Users/alex/Repos/polarity/neontetra/node_modules/eslint-plugin-decorator-position/lib/rules/decorator-position.js:154:24)
    at ClassProperty[decorators.length=1]:exit (/Users/alex/Repos/polarity/neontetra/node_modules/eslint-plugin-decorator-position/lib/rules/decorator-position.js:127:7)
    at /Users/alex/Repos/polarity/neontetra/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/alex/Repos/polarity/neontetra/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/alex/Repos/polarity/neontetra/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Error Line
```
  @(task(function* () {
	// some task
  }).drop())
  someTask;
```

Version Info, no custom configuration...using out-of-the-box defaults
```
eslint-plugin-decorator-position@^2.0.1:
  version "2.0.1"
  resolved "https://registry.yarnpkg.com/eslint-plugin-decorator-position/-/eslint-plugin-decorator-position-2.0.1.tgz#7340cf5bd68edaef257cea5b61c4951be0e6c3bc"
  integrity sha512-Uv3XnRmFO0YIoH7mzijeUGo0P5To5+bFOq7qrN2wOkIsNS//UR+JrqXv5cm3GVJCj50VfqkbgMutQmZGXK94yA==
  dependencies:
    "@ember-data/rfc395-data" "^0.0.4"
    ember-rfc176-data "^0.3.12"
    snake-case "^3.0.3"
```

**Comment by NullVoxPopuli** [comment]
thanks for reporting!


when trying to make a reproduction, a noticing some error, I accidentally fixed it! 
I'll get this released right away.
