### ISSUE TITLE
Cannot read property 'printWidth' of undefined with Prettier 2.2.0

### ISSUE THREAD

**Issue by EvgenyOrekhov** [NullVoxPopuli/eslint-plugin-decorator-position#214]
This error appeared when I upgraded Prettier to 2.2.0:

```text
❯ eslint .

Oops! Something went wrong! :(

ESLint: 7.14.0

TypeError: Error while loading rule 'decorator-position/decorator-position': Cannot read property 'printWidth' of undefined
Occurred while linting C:\eslint-config-hardcore\sort-class-members-test.js
    at lineLength (C:\eslint-config-hardcore\node_modules\eslint-plugin-decorator-position\lib\rules\decorator-position.js:337:59)       
    at Object.decoratorPositionRule [as create] (C:\eslint-config-hardcore\node_modules\eslint-plugin-decorator-position\lib\rules\decorator-position.js:142:26)
```

**Comment by NullVoxPopuli** [comment]
smoke-test issue-reproductions/#196 is currently reproducing this :+1:

I'm starting to think I just have the tests run on a cron
